### ISSUE TITLE
Restrict GitHub permission

### ISSUE THREAD

**Issue by mzfr** [tamland/kodi-addon-submission#1]
I think we should only ask for permissions that are actually needed for the whole process. 
Currently this ask for all the permissions of all the public repository meaning this application will be able to make any changes in those repos.

**Comment by tamland** [comment]
This is a github limitation. Afaik. they don't provide any scopes for read-only or write to specific repositories. It's read/write to all, or nothing.

https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes
